<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ai63aI_' shared service.

return $this->privates['.service_locator.Ai63aI_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\UserController::add' => ['privates', '.service_locator.A86eU2e', 'get_ServiceLocator_A86eU2eService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.xDtsfeN', 'get_ServiceLocator_XDtsfeNService.php', true],
    'App\\Controller\\UserController::read' => ['privates', '.service_locator.xDtsfeN', 'get_ServiceLocator_XDtsfeNService.php', true],
    'App\\Controller\\UserController::update' => ['privates', '.service_locator.A86eU2e', 'get_ServiceLocator_A86eU2eService.php', true],
    'App\\Controller\\UserController:add' => ['privates', '.service_locator.A86eU2e', 'get_ServiceLocator_A86eU2eService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.xDtsfeN', 'get_ServiceLocator_XDtsfeNService.php', true],
    'App\\Controller\\UserController:read' => ['privates', '.service_locator.xDtsfeN', 'get_ServiceLocator_XDtsfeNService.php', true],
    'App\\Controller\\UserController:update' => ['privates', '.service_locator.A86eU2e', 'get_ServiceLocator_A86eU2eService.php', true],
], [
    'App\\Controller\\UserController::add' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::read' => '?',
    'App\\Controller\\UserController::update' => '?',
    'App\\Controller\\UserController:add' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:read' => '?',
    'App\\Controller\\UserController:update' => '?',
]);
