<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xDtsfeN' shared service.

return $this->privates['.service_locator.xDtsfeN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService.php', true],
], [
    'dm' => '?',
]);
