<?php

namespace App\Form\Type;

use Doctrine\ODM\MongoDB\DocumentManager as DocumentManager;
use App\Document\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
            $builder
                ->add("email",TextType::class,['label'=>'Mail'])
                ->add("firstname",TextType::class,['label'=>'Prenom'])
                ->add("lastname",TextType::class,['label'=>'Nom'])
                ->add("rawpassword",RepeatedType::class,['type'=>PasswordType::class,'first_options' => ['label' => 'Mot de passe'],
                    'second_options' => ['label' => 'Confirmez le mot de passe']]);
    }
}