<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['firstname']) || (! empty($this->class->fieldMappings['firstname']['nullable']) && array_key_exists('firstname', $data))) {
            $value = $data['firstname'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['firstname']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['firstname']->setValue($document, $return);
            $hydratedData['firstname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lastname']) || (! empty($this->class->fieldMappings['lastname']['nullable']) && array_key_exists('lastname', $data))) {
            $value = $data['lastname'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['lastname']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['lastname']->setValue($document, $return);
            $hydratedData['lastname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email']) || (! empty($this->class->fieldMappings['email']['nullable']) && array_key_exists('email', $data))) {
            $value = $data['email'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['email']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['rawpassword']) || (! empty($this->class->fieldMappings['rawpassword']['nullable']) && array_key_exists('rawpassword', $data))) {
            $value = $data['rawpassword'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['rawpassword']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['rawpassword']->setValue($document, $return);
            $hydratedData['rawpassword'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['creation_date'])) {
            $value = $data['creation_date'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['creation_date']->setValue($document, clone $return);
            $hydratedData['creation_date'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['password']) || (! empty($this->class->fieldMappings['password']['nullable']) && array_key_exists('password', $data))) {
            $value = $data['password'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['password']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['password']->setValue($document, $return);
            $hydratedData['password'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isAdmin']) || (! empty($this->class->fieldMappings['isAdmin']['nullable']) && array_key_exists('isAdmin', $data))) {
            $value = $data['isAdmin'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['isAdmin']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['isAdmin']->setValue($document, $return);
            $hydratedData['isAdmin'] = $return;
        }
        return $hydratedData;
    }
}