<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNnNRKb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNnNRKb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSNnNRKb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSNnNRKb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSNnNRKb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SNnNRKb',
    'container.build_id' => '375aafc8',
    'container.build_time' => 1572822065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNnNRKb');
