<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_connection' shared service.

include_once $this->targetDirs[3].'/vendor/mongodb/mongodb/src/Client.php';

return $this->services['doctrine_mongodb.odm.default_connection'] = new \MongoDB\Client($this->getEnv('resolve:MONGODB_URL'), [], ['typeMap' => ['root' => 'array', 'document' => 'array']]);
